### ISSUE TITLE
Change Czechoslovakia to Czech Republic-Slovakia

### ISSUE THREAD

**Issue by rg02kg** [tdwg/geoschemes#20]
Czechoslovakia  no longer exists, there are a number of options here, Ideally they should be 2 new level 3 regions, but that may be disruptive.

**Comment by PacoPando** [comment]
Czechoslovakia is not in existence since 1993.  The constitution of Slovakia and the Czech Republic was acknowledged in the World Geographical Scheme for Recording Plant Distributions (WGSRPD-2, 2001), and I do not think we should change that, and keep maintaining  Slovakia and the Czech Republic as level 4 units, as is the case with other countries such as Belgium, Luxembourg or the Baltic Republics, for instance
